name: slicereparam

channels:
    - defaults
    - conda-forge

dependencies: 
    - conda-build
    - pip

    # Package dependencies
    - numpy
    - scipy
    - scikit-learn
    
    # Executable dependencies
    - ipykernel
    - ipywidgets
    - matplotlib

    - pip: 
      - jax
      - jaxlib
      - autograd